#!/bin/bash

function network_head () {
    echo '=========== NETWORK ============'
    echo 'Define Network Design: '
    NETWORK=./network/network_var.sh
}
network_head

# CONTROLLER

function CONTROLLER_PROVIDER_INT () {
    read -p 'CONTROLLER PROVIDER INTERFACE NAME (ex: eth0/enp2s0/ens33): ' CONTROLLER_PROVIDER_INT
    echo 'CONTROLLER_PROVIDER_INT='$CONTROLLER_PROVIDER_INT >> $NETWORK
}
CONTROLLER_PROVIDER_INT

function CONTROLLER_MANAGEMENT_IP () {
    read -p 'CONTROLLER MANAGEMENT IP ADDRESS (ex: 192.168.100.100): ' CONTROLLER_MANAGEMENT_IP
    echo 'CONTROLLER_MANAGEMENT_IP='$CONTROLLER_MANAGEMENT_IP >> $NETWORK
}
CONTROLLER_MANAGEMENT_IP

function CONTROLLER_PROVIDER_IP () {
    read -p 'CONTROLLER PROVIDER IP ADDRESS (ex: 10.1.1.10): ' CONTROLLER_PROVIDER_IP
    echo 'CONTROLLER_PROVIDER_IP='$CONTROLLER_PROVIDER_IP >> $NETWORK
}
CONTROLLER_PROVIDER_IP

# COMPUTE

function COMPUTE_PROVIDER_INT () {
    read -p 'COMPUTE PROVIDER INTERFACE NAME (ex: eth0/enp2s0/ens33): ' COMPUTE_PROVIDER_INT
    echo 'COMPUTE_PROVIDER_INT='$COMPUTE_PROVIDER_INT >> $NETWORK
}
COMPUTE_PROVIDER_INT

function COMPUTE_MANAGEMENT_IP () {
    read -p 'COMPUTE MANAGEMENT IP ADDRESS (ex: 192.168.100.200): ' COMPUTE_MANAGEMENT_IP
    echo 'COMPUTE_MANAGEMENT_IP='$COMPUTE_MANAGEMENT_IP >> $NETWORK
}
COMPUTE_MANAGEMENT_IP

function COMPUTE_PROVIDER_IP () {
    read -p 'COMPUTE PROVIDER IP ADDRESS (ex: 10.1.1.20): ' COMPUTE_PROVIDER_IP
    echo 'COMPUTE_PROVIDER_IP='$COMPUTE_PROVIDER_IP >> $NETWORK
}
COMPUTE_PROVIDER_IP



chmod +x network/network_var.sh
