#!/bin/bash

function network_head () {
    echo '=========== NETWORK ============'
    echo 'Define Network Design: '
    NETWORK=./network/network_var.sh
}
network_head

function CONTROLLER_PROVIDER_IP () {
    read -p 'CONTROLLER PROVIDER IP ADDRESS: ' CONTROLLER_PROVIDER_IP
    echo 'CONTROLLER_PROVIDER_IP='$CONTROLLER_PROVIDER_IP >> $NETWORK
}
CONTROLLER_PROVIDER_IP

function CONTROLLER_MANAGEMENT_IP () {
    read -p 'CONTROLLER MANAGEMENT IP ADDRESS: ' CONTROLLER_MANAGEMENT_IP
    echo 'CONTROLLER_MANAGEMENT_IP='$CONTROLLER_MANAGEMENT_IP >> $NETWORK
}
CONTROLLER_MANAGEMENT_IP

function COMPUTE_PROVIDER_IP () {
    read -p 'COMPUTE PROVIDER IP ADDRESS: ' COMPUTE_PROVIDER_IP
    echo 'COMPUTE_PROVIDER_IP='$COMPUTE_PROVIDER_IP >> $NETWORK
}
COMPUTE_PROVIDER_IP

function COMPUTE_MANAGEMENT_IP () {
    read -p 'COMPUTE MANAGEMENT IP ADDRESS: ' COMPUTE_MANAGEMENT_IP
    echo 'COMPUTE_MANAGAMENT_IP='$COMPUTE_MANAGEMENT_IP >> $NETWORK
}
COMPUTE_MANAGEMENT_IP

chmod +x network/network_var.sh